import type { Metadata } from "next";
import { auth } from '@/lib/auth'
import { Geist, Geist_Mono } from "next/font/google";
import SessionProvider from '@/lib/contexts/sessionProvider'
import "./globals.css";
import ThemeProvider from "@/lib/contexts/themeProvider";
import WebVitals from "@/lib/webvitals";
import { GoogleAnalytics } from "@/lib/analytic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="w-full h-full">
       <ThemeProvider>
        <SessionProvider session={session}>
          <GoogleAnalytics/>
          <WebVitals/>
        {children}
       </SessionProvider>
       </ThemeProvider>
       </body>
    </html>
  );
}
