import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { products } from "../db/schema";
import { db } from "../db"

const seedProducts = [
    // ───── MENS ─────
    {
        name: "Classic White Kurta",
        description: "Comfortable cotton kurta perfect for casual and festive wear.",
        price: "799",
        category: "mens",
        occasion: "casual",
        imageUrl: "https://picsum.photos/seed/kurta1/400/400",
        stock: 25,
    },
    {
        name: "Slim Fit Chinos",
        description: "Versatile chinos that work for office and casual outings.",
        price: "1299",
        category: "mens",
        occasion: "office",
        imageUrl: "https://picsum.photos/seed/chinos1/400/400",
        stock: 18,
    },
    {
        name: "Wedding Sherwani",
        description: "Elegant sherwani with intricate embroidery for wedding occasions.",
        price: "4999",
        category: "mens",
        occasion: "wedding",
        imageUrl: "https://picsum.photos/seed/sherwani1/400/400",
        stock: 8,
    },
    {
        name: "Casual Linen Shirt",
        description: "Breathable linen shirt ideal for summer outings.",
        price: "899",
        category: "mens",
        occasion: "casual",
        imageUrl: "https://picsum.photos/seed/shirt1/400/400",
        stock: 30,
    },
    {
        name: "Formal Blazer",
        description: "Sharp blazer for office meetings and formal events.",
        price: "2999",
        category: "mens",
        occasion: "office",
        imageUrl: "https://picsum.photos/seed/blazer1/400/400",
        stock: 12,
    },
    {
        name: "Party Wear Jodhpuri",
        description: "Stylish Jodhpuri suit perfect for parties and receptions.",
        price: "3499",
        category: "mens",
        occasion: "party",
        imageUrl: "https://picsum.photos/seed/jodhpuri1/400/400",
        stock: 6,
    },
    {
        name: "Printed Casual Tshirt",
        description: "Graphic tee for everyday casual wear.",
        price: "399",
        category: "mens",
        occasion: "casual",
        imageUrl: "https://picsum.photos/seed/tshirt1/400/400",
        stock: 50,
    },
    {
        name: "Nehru Jacket",
        description: "Classic Nehru jacket to layer over kurtas for festive occasions.",
        price: "1499",
        category: "mens",
        occasion: "wedding",
        imageUrl: "https://picsum.photos/seed/nehru1/400/400",
        stock: 14,
    },
    {
        name: "Office Formal Trousers",
        description: "Tailored formal trousers for a professional look.",
        price: "1199",
        category: "mens",
        occasion: "office",
        imageUrl: "https://picsum.photos/seed/trousers1/400/400",
        stock: 20,
    },
    {
        name: "Denim Jacket",
        description: "Classic denim jacket for casual outings.",
        price: "1799",
        category: "mens",
        occasion: "casual",
        imageUrl: "https://picsum.photos/seed/denim1/400/400",
        stock: 22,
    },

    // ───── WOMENS ─────
    {
        name: "Floral Anarkali Suit",
        description: "Beautiful floral Anarkali suit for festive and wedding occasions.",
        price: "2499",
        category: "womens",
        occasion: "wedding",
        imageUrl: "https://picsum.photos/seed/anarkali1/400/400",
        stock: 10,
    },
    {
        name: "Casual Kurti",
        description: "Light cotton kurti for everyday wear.",
        price: "599",
        category: "womens",
        occasion: "casual",
        imageUrl: "https://picsum.photos/seed/kurti1/400/400",
        stock: 40,
    },
    {
        name: "Office Formal Blazer",
        description: "Structured blazer for a sharp office look.",
        price: "2299",
        category: "womens",
        occasion: "office",
        imageUrl: "https://picsum.photos/seed/wblaze1/400/400",
        stock: 15,
    },
    {
        name: "Silk Saree",
        description: "Pure silk saree with zari border for weddings.",
        price: "3999",
        category: "womens",
        occasion: "wedding",
        imageUrl: "https://picsum.photos/seed/saree1/400/400",
        stock: 7,
    },
    {
        name: "Party Wear Gown",
        description: "Elegant floor-length gown for parties and events.",
        price: "2999",
        category: "womens",
        occasion: "party",
        imageUrl: "https://picsum.photos/seed/gown1/400/400",
        stock: 9,
    },
    {
        name: "Casual Palazzo Set",
        description: "Comfy palazzo set for casual everyday use.",
        price: "799",
        category: "womens",
        occasion: "casual",
        imageUrl: "https://picsum.photos/seed/palazzo1/400/400",
        stock: 35,
    },
    {
        name: "Formal Pencil Skirt",
        description: "Classic pencil skirt for office and formal meetings.",
        price: "1099",
        category: "womens",
        occasion: "office",
        imageUrl: "https://picsum.photos/seed/skirt1/400/400",
        stock: 18,
    },
    {
        name: "Embroidered Lehenga",
        description: "Heavy embroidered lehenga for weddings and receptions.",
        price: "4799",
        category: "womens",
        occasion: "wedding",
        imageUrl: "https://picsum.photos/seed/lehenga1/400/400",
        stock: 5,
    },
    {
        name: "Cocktail Dress",
        description: "Chic cocktail dress for parties and evening events.",
        price: "1999",
        category: "womens",
        occasion: "party",
        imageUrl: "https://picsum.photos/seed/cocktail1/400/400",
        stock: 11,
    },
    {
        name: "Casual Printed Dress",
        description: "Breezy printed dress for casual outings.",
        price: "899",
        category: "womens",
        occasion: "casual",
        imageUrl: "https://picsum.photos/seed/dress1/400/400",
        stock: 28,
    },

    // ───── ELECTRONICS ─────
    {
        name: "Wireless Bluetooth Earbuds",
        description: "True wireless earbuds with noise cancellation and 24hr battery.",
        price: "1999",
        category: "electronics",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/earbuds1/400/400",
        stock: 45,
    },
    {
        name: "Mechanical Keyboard",
        description: "Tactile mechanical keyboard for developers and gamers.",
        price: "2999",
        category: "electronics",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/keyboard1/400/400",
        stock: 20,
    },
    {
        name: "Portable Power Bank 20000mAh",
        description: "Fast charging power bank with dual USB-C output.",
        price: "1299",
        category: "electronics",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/powerbank1/400/400",
        stock: 60,
    },
    {
        name: "Smart Watch",
        description: "Fitness tracking smartwatch with heart rate and SpO2 monitor.",
        price: "3499",
        category: "electronics",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/watch1/400/400",
        stock: 25,
    },
    {
        name: "USB-C Hub 7-in-1",
        description: "Multi-port hub with HDMI, USB 3.0, SD card reader.",
        price: "1499",
        category: "electronics",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/hub1/400/400",
        stock: 30,
    },
    {
        name: "Laptop Stand",
        description: "Adjustable aluminium laptop stand for ergonomic setup.",
        price: "899",
        category: "electronics",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/stand1/400/400",
        stock: 40,
    },
    {
        name: "Webcam 1080p",
        description: "Full HD webcam with built-in mic for video calls.",
        price: "1999",
        category: "electronics",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/webcam1/400/400",
        stock: 22,
    },
    {
        name: "Wireless Mouse",
        description: "Ergonomic wireless mouse with silent clicks.",
        price: "699",
        category: "electronics",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/mouse1/400/400",
        stock: 55,
    },
    {
        name: "Noise Cancelling Headphones",
        description: "Over-ear headphones with active noise cancellation.",
        price: "4499",
        category: "electronics",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/headphones1/400/400",
        stock: 15,
    },
    {
        name: "Portable Bluetooth Speaker",
        description: "Waterproof speaker with 12hr playtime.",
        price: "1799",
        category: "electronics",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/speaker1/400/400",
        stock: 33,
    },

    // ───── GIFTS ─────
    {
        name: "Scented Candle Gift Set",
        description: "Set of 3 luxury scented candles — perfect gift for anyone.",
        price: "499",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/candle1/400/400",
        stock: 50,
    },
    {
        name: "Leather Wallet for Men",
        description: "Slim genuine leather wallet — great gift for dad or brother.",
        price: "799",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/wallet1/400/400",
        stock: 40,
    },
    {
        name: "Personalised Photo Frame",
        description: "Custom engraved photo frame for special memories.",
        price: "399",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/frame1/400/400",
        stock: 35,
    },
    {
        name: "Skincare Gift Hamper",
        description: "Curated skincare set with face wash, moisturiser, and serum.",
        price: "1299",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/skincare1/400/400",
        stock: 20,
    },
    {
        name: "Coffee Mug with Quote",
        description: "Ceramic mug with funny quote — perfect office desk gift.",
        price: "299",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/mug1/400/400",
        stock: 70,
    },
    {
        name: "Fitness Band",
        description: "Basic fitness tracker — good entry-level gift for health-conscious people.",
        price: "999",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/fitnessband1/400/400",
        stock: 28,
    },
    {
        name: "Desk Organiser Set",
        description: "Wooden desk organiser set — great gift for office workers.",
        price: "599",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/organiser1/400/400",
        stock: 25,
    },
    {
        name: "Book Set — Self Help",
        description: "Curated set of 3 bestselling self-help books.",
        price: "899",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/books1/400/400",
        stock: 30,
    },
    {
        name: "Chocolate Gift Box",
        description: "Premium assorted chocolate box — universally loved gift.",
        price: "449",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/choc1/400/400",
        stock: 60,
    },
    {
        name: "Jewellery Box for Her",
        description: "Elegant jewellery organiser box — perfect gift for mom or wife.",
        price: "699",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/jewbox1/400/400",
        stock: 22,
    },
    {
        name: "Succulent Plant Kit",
        description: "Mini succulent plant with pot — unique and lasting gift.",
        price: "349",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/plant1/400/400",
        stock: 45,
    },
    {
        name: "Stainless Steel Water Bottle",
        description: "Insulated bottle that keeps drinks hot/cold for 24hrs.",
        price: "599",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/bottle1/400/400",
        stock: 55,
    },
    {
        name: "Tie and Pocket Square Set",
        description: "Elegant tie and pocket square combo — great gift for dad.",
        price: "499",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/tie1/400/400",
        stock: 30,
    },
    {
        name: "Perfume Gift Set",
        description: "Set of 3 mini perfumes — great gift for her.",
        price: "999",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/perfume1/400/400",
        stock: 18,
    },
    {
        name: "Wireless Charging Pad",
        description: "10W fast wireless charger — practical everyday gift.",
        price: "799",
        category: "gifts",
        occasion: null,
        imageUrl: "https://picsum.photos/seed/charger1/400/400",
        stock: 40,
    },
];

async function main() {
    console.log("🌱 Seeding database...");

    const rows = seedProducts.map((p) => ({
        id: crypto.randomUUID(),
        name: p.name,
        description: p.description,
        price: p.price,
        category: p.category,
        occasion: p.occasion,
        imageUrl: p.imageUrl,
        stock: p.stock,
        inStock: p.stock > 0,
    }));

    await db.insert(products).values(rows);

    console.log(`✅ Seeded ${rows.length} products successfully.`);
    process.exit(0);
}

main().catch((err) => {
    console.error("❌ Seed failed:", err);
    process.exit(1);
});